# Generated by Django 4.2.27 on 2025-12-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Administrator'), ('EMPLOYEE', 'Employee'), ('SAFETY_MANAGER', 'Safety Manager'), ('LOCATION_HEAD', 'Location Head'), ('PLANT_HEAD', 'Plant Head'), ('HOD', 'Head of Department')], default='EMPLOYEE', max_length=20, null=True),
        ),
    ]
