# Generated by Django 4.2.27 on 2025-12-12 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_location_options_zone_and_more'),
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='organizations.zone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Administrator'), ('EMPLOYEE', 'Employee'), ('SAFETY_MANAGER', 'Safety Manager'), ('LOCATION_HEAD', 'Location Head'), ('PLANT_HEAD', 'Plant Head'), ('HOD', 'Head of Department')], max_length=20, null=True),
        ),
    ]
