# Generated by Django 4.2.27 on 2025-12-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_zone_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_approve_hazards',
            field=models.BooleanField(default=False, help_text='Can approve/reject hazard reports'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_approve_incidents',
            field=models.BooleanField(default=False, help_text='Can approve/reject incident reports'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_close_incidents',
            field=models.BooleanField(default=False, help_text='Can close completed incidents'),
        ),
    ]
