# Generated by Django 4.2.27 on 2025-12-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_can_approve_hazards_user_can_approve_incidents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_access_audit_module',
            field=models.BooleanField(default=False, help_text='User can perform safety audits', verbose_name='Can Access Audit Module'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_access_hazard_module',
            field=models.BooleanField(default=False, help_text='User can report and view hazards', verbose_name='Can Access Hazard Module'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_access_incident_module',
            field=models.BooleanField(default=False, help_text='User can report and view incidents', verbose_name='Can Access Incident Module'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_access_inspection_module',
            field=models.BooleanField(default=False, help_text='User can conduct safety inspections', verbose_name='Can Access Inspection Module'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_access_observation_module',
            field=models.BooleanField(default=False, help_text='User can submit safety observations', verbose_name='Can Access Observation Module'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_access_permit_module',
            field=models.BooleanField(default=False, help_text='User can request work permits', verbose_name='Can Access Permit Module'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_access_reports_module',
            field=models.BooleanField(default=False, help_text='User can view and generate reports', verbose_name='Can Access Reports Module'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_access_training_module',
            field=models.BooleanField(default=False, help_text='User can access training materials', verbose_name='Can Access Training Module'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_approve_inspections',
            field=models.BooleanField(default=False, help_text='User can approve inspection reports', verbose_name='Can Approve Inspections'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_approve_permits',
            field=models.BooleanField(default=False, help_text='User can approve work permit requests', verbose_name='Can Approve Permits'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_close_hazards',
            field=models.BooleanField(default=False, help_text='User can close resolved hazards', verbose_name='Can Close Hazards'),
        ),
        migrations.AlterField(
            model_name='user',
            name='can_approve_hazards',
            field=models.BooleanField(default=False, help_text='User can approve/reject hazard reports', verbose_name='Can Approve Hazards'),
        ),
        migrations.AlterField(
            model_name='user',
            name='can_approve_incidents',
            field=models.BooleanField(default=False, help_text='User can approve/reject incident reports', verbose_name='Can Approve Incidents'),
        ),
        migrations.AlterField(
            model_name='user',
            name='can_close_incidents',
            field=models.BooleanField(default=False, help_text='User can close completed incidents', verbose_name='Can Close Incidents'),
        ),
    ]
