# Generated by Django 4.2.27 on 2025-12-22 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_alter_sublocation_code'),
        ('accounts', '0005_user_can_access_audit_module_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sublocation',
            field=models.ForeignKey(blank=True, help_text='Optional: Specific sub-location assigned to user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='organizations.sublocation'),
        ),
    ]
