# Generated by Django 4.2.27 on 2025-12-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_sublocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text="Employee's date of birth", null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='user',
            name='employment_type',
            field=models.CharField(choices=[('FULL_TIME', 'Full-time'), ('PART_TIME', 'Part-time'), ('CONTRACT', 'Contract'), ('TEMPORARY', 'Temporary'), ('INTERN', 'Intern'), ('CONSULTANT', 'Consultant')], default='FULL_TIME', max_length=20, verbose_name='Employment Type'),
        ),
        migrations.AddField(
            model_name='user',
            name='job_title',
            field=models.CharField(blank=True, help_text="Employee's job title/designation", max_length=100, null=True, verbose_name='Job Title'),
        ),
    ]
