# Generated by Django 4.2.27 on 2025-12-31 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_alter_sublocation_unique_together'),
        ('accounts', '0008_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_locations',
            field=models.ManyToManyField(blank=True, help_text='Multiple locations this user manages/has access to', related_name='assigned_users_location', to='organizations.location', verbose_name='Assigned Locations'),
        ),
        migrations.AddField(
            model_name='user',
            name='assigned_plants',
            field=models.ManyToManyField(blank=True, help_text='Multiple plants this user manages/has access to', related_name='assigned_users_plant', to='organizations.plant', verbose_name='Assigned Plants'),
        ),
        migrations.AddField(
            model_name='user',
            name='assigned_sublocations',
            field=models.ManyToManyField(blank=True, help_text='Multiple sub-locations this user manages/has access to', related_name='assigned_users_sublocation', to='organizations.sublocation', verbose_name='Assigned Sub-Locations'),
        ),
        migrations.AddField(
            model_name='user',
            name='assigned_zones',
            field=models.ManyToManyField(blank=True, help_text='Multiple zones this user manages/has access to', related_name='assigned_users_zone', to='organizations.zone', verbose_name='Assigned Zones'),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Primary location assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='organizations.location', verbose_name='Primary Location'),
        ),
        migrations.AlterField(
            model_name='user',
            name='plant',
            field=models.ForeignKey(blank=True, help_text='Primary plant assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='organizations.plant', verbose_name='Primary Plant'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sublocation',
            field=models.ForeignKey(blank=True, help_text='Primary sub-location assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='organizations.sublocation', verbose_name='Primary Sub-Location'),
        ),
        migrations.AlterField(
            model_name='user',
            name='zone',
            field=models.ForeignKey(blank=True, help_text='Primary zone assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='organizations.zone', verbose_name='Primary Zone'),
        ),
    ]
