# Generated by Django 4.2.27 on 2025-12-12 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0003_alter_location_options_zone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('incident_type', models.CharField(choices=[('LTI', 'Lost Time Injury (LTI)'), ('MTC', 'Medical Treatment Case (MTC/RWC)'), ('FA', 'First Aid (FA)'), ('HLFI', 'High Lost Frequency Injury (HLFI)')], max_length=10)),
                ('incident_date', models.DateField()),
                ('incident_time', models.TimeField()),
                ('incident_title', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='Detailed description of what happened')),
                ('severity_level', models.CharField(choices=[('Minor', 'Minor'), ('Moderate', 'Moderate'), ('Serious', 'Serious'), ('Critical', 'Critical'), ('Fatal', 'Fatal')], max_length=20)),
                ('affected_person_name', models.CharField(max_length=200)),
                ('affected_person_employee_id', models.CharField(blank=True, max_length=50)),
                ('affected_body_parts', models.JSONField(blank=True, default=list)),
                ('nature_of_injury', models.TextField(blank=True)),
                ('witnesses', models.TextField(blank=True, help_text='Names of witnesses')),
                ('immediate_actions_taken', models.TextField(blank=True)),
                ('first_aid_provided', models.BooleanField(default=False)),
                ('hospitalization_required', models.BooleanField(default=False)),
                ('hospital_name', models.CharField(blank=True, max_length=200)),
                ('reported_date', models.DateTimeField(auto_now_add=True)),
                ('investigation_required', models.BooleanField(default=True)),
                ('investigation_deadline', models.DateField(blank=True, null=True)),
                ('investigation_completed_date', models.DateField(blank=True, null=True)),
                ('root_cause', models.TextField(blank=True)),
                ('contributing_factors', models.TextField(blank=True)),
                ('action_plan', models.TextField(blank=True)),
                ('action_plan_deadline', models.DateField(blank=True, null=True)),
                ('action_plan_status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('status', models.CharField(choices=[('REPORTED', 'Reported'), ('INVESTIGATION_PENDING', 'Investigation Pending'), ('UNDER_INVESTIGATION', 'Under Investigation'), ('ACTION_PLAN_PENDING', 'Action Plan Pending'), ('ACTION_IN_PROGRESS', 'Action in Progress'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed')], default='REPORTED', max_length=30)),
                ('safety_manager_notified', models.BooleanField(default=False)),
                ('location_head_notified', models.BooleanField(default=False)),
                ('plant_head_notified', models.BooleanField(default=False)),
                ('closure_date', models.DateField(blank=True, null=True)),
                ('closure_remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_plan_responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_action_responsible', to=settings.AUTH_USER_MODEL)),
                ('affected_person_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_affected', to='organizations.department')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_assigned', to=settings.AUTH_USER_MODEL)),
                ('investigator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_investigated', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='organizations.location')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='organizations.plant')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents_reported', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='organizations.zone')),
            ],
            options={
                'verbose_name': 'Incident Report',
                'verbose_name_plural': 'Incident Reports',
                'ordering': ['-incident_date', '-incident_time'],
            },
        ),
        migrations.CreateModel(
            name='IncidentPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='incident_photos/%Y/%m/')),
                ('photo_type', models.CharField(choices=[('INCIDENT_SCENE', 'Incident Scene'), ('INJURY', 'Injury Photo'), ('EVIDENCE', 'Evidence'), ('CORRECTIVE_ACTION', 'Corrective Action')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='accidents.incident')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentInvestigationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investigation_date', models.DateField()),
                ('investigation_team', models.TextField(help_text='Names of investigation team members')),
                ('sequence_of_events', models.TextField()),
                ('root_cause_analysis', models.TextField()),
                ('contributing_factors', models.TextField()),
                ('unsafe_conditions_identified', models.TextField(blank=True)),
                ('unsafe_acts_identified', models.TextField(blank=True)),
                ('evidence_collected', models.TextField(blank=True)),
                ('witness_statements', models.TextField(blank=True)),
                ('immediate_corrective_actions', models.TextField()),
                ('preventive_measures', models.TextField()),
                ('long_term_recommendations', models.TextField(blank=True)),
                ('action_items', models.TextField(help_text='Specific action items with responsibilities')),
                ('target_completion_date', models.DateField()),
                ('completed_date', models.DateField()),
                ('reviewed_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigation_reports_completed', to=settings.AUTH_USER_MODEL)),
                ('incident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investigation_report', to='accidents.incident')),
                ('investigator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigations_conducted', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigation_reports_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Investigation Report',
                'verbose_name_plural': 'Investigation Reports',
            },
        ),
        migrations.CreateModel(
            name='IncidentActionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_description', models.TextField()),
                ('target_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=20)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('completion_remarks', models.TextField(blank=True)),
                ('verification_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='accidents.incident')),
                ('responsible_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_actions_responsible', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_actions_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['target_date'],
            },
        ),
    ]
