# Generated by Django 4.2.27 on 2025-12-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='near_miss_type',
            field=models.CharField(blank=True, choices=[('UNSAFE_CONDITION', 'Unsafe Condition'), ('UNSAFE_ACT', 'Unsafe Act')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='potential_consequences',
            field=models.TextField(blank=True, help_text='What could have happened?'),
        ),
        migrations.AddField(
            model_name='incident',
            name='potential_severity',
            field=models.CharField(blank=True, choices=[('Low', 'Low - Minor injury possible'), ('Medium', 'Medium - Moderate injury possible'), ('High', 'High - Serious injury possible'), ('Critical', 'Critical - Fatality possible')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_type',
            field=models.CharField(choices=[('LTI', 'Lost Time Injury (LTI)'), ('MTC', 'Medical Treatment Case (MTC/RWC)'), ('FA', 'First Aid (FA)'), ('HLFI', 'High Lost Frequency Injury (HLFI)'), ('NM', 'Near Miss (NM)')], max_length=10),
        ),
    ]
