# Generated by Django 4.2.27 on 2025-12-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0002_incident_near_miss_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='behalf_reporter_email',
            field=models.EmailField(blank=True, help_text='Your email for updates on this report', max_length=254, verbose_name='Your Email (Person Reporting)'),
        ),
        migrations.AddField(
            model_name='incident',
            name='behalf_reporter_name',
            field=models.CharField(blank=True, help_text='Your name as the person filing this report', max_length=255, verbose_name='Your Name (Person Reporting)'),
        ),
        migrations.AddField(
            model_name='incident',
            name='behalf_reporter_phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Your Phone (Person Reporting)'),
        ),
        migrations.AddField(
            model_name='incident',
            name='behalf_reporter_relationship',
            field=models.CharField(blank=True, help_text='e.g., Supervisor, Colleague, Safety Officer, Witness', max_length=100, verbose_name='Your Relationship to Affected Person'),
        ),
        migrations.AddField(
            model_name='incident',
            name='is_reported_on_behalf',
            field=models.BooleanField(default=False, help_text='Check if you are reporting this incident for another person', verbose_name='Reported on behalf of someone'),
        ),
    ]
