# Generated by Django 4.2.27 on 2025-12-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0003_incident_behalf_reporter_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='near_miss_type',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='potential_consequences',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='potential_severity',
        ),
        migrations.AddField(
            model_name='incident',
            name='unsafe_acts',
            field=models.JSONField(blank=True, default=list, help_text='List of unsafe acts that contributed to the incident'),
        ),
        migrations.AddField(
            model_name='incident',
            name='unsafe_conditions',
            field=models.JSONField(blank=True, default=list, help_text='List of unsafe conditions that contributed to the incident'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_type',
            field=models.CharField(choices=[('LTI', 'Lost Time Injury (LTI)'), ('MTC', 'Medical Treatment Case (MTC/RWC)'), ('FA', 'First Aid (FA)'), ('HLFI', 'High Lost Frequency Injury (HLFI)')], max_length=10),
        ),
    ]
