# Generated by Django 4.2.27 on 2025-12-20 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_location_options_zone_and_more'),
        ('accidents', '0004_remove_incident_near_miss_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='behalf_reporter_email',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='behalf_reporter_phone',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='behalf_reporter_relationship',
        ),
        migrations.AddField(
            model_name='incident',
            name='behalf_reporter_department',
            field=models.ForeignKey(blank=True, help_text='Your department as the person filing this report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_reported_on_behalf', to='organizations.department', verbose_name='Your Department (Person Reporting)'),
        ),
    ]
