# Generated by Django 4.2.27 on 2025-12-23 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0006_incidentinvestigationreport_job_factors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentinvestigationreport',
            name='job_factors',
        ),
        migrations.RemoveField(
            model_name='incidentinvestigationreport',
            name='personal_factors',
        ),
    ]
