# Generated by Django 4.2.27 on 2025-12-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0007_remove_incidentinvestigationreport_job_factors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentinvestigationreport',
            name='job_factors',
            field=models.JSONField(blank=True, default=list, help_text='Job factors contributing to the incident (from checkbox selection)'),
        ),
        migrations.AddField(
            model_name='incidentinvestigationreport',
            name='personal_factors',
            field=models.JSONField(blank=True, default=list, help_text='Personal factors contributing to the incident (from checkbox selection)'),
        ),
    ]
