# Generated by Django 4.2.27 on 2025-12-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0008_incidentinvestigationreport_job_factors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='affected_person_age',
            field=models.IntegerField(blank=True, help_text='Age calculated from date of birth', null=True, verbose_name='Age'),
        ),
        migrations.AddField(
            model_name='incident',
            name='affected_person_dob',
            field=models.DateField(blank=True, help_text="Affected person's date of birth", null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='incident',
            name='affected_person_employment_type',
            field=models.CharField(blank=True, choices=[('FULL_TIME', 'Full-time'), ('PART_TIME', 'Part-time'), ('CONTRACT', 'Contract'), ('TEMPORARY', 'Temporary'), ('INTERN', 'Intern'), ('CONSULTANT', 'Consultant')], max_length=20, null=True, verbose_name='Employment Type'),
        ),
        migrations.AddField(
            model_name='incident',
            name='affected_person_gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('PREFER_NOT_TO_SAY', 'Prefer not to say')], max_length=20, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='incident',
            name='affected_person_job_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Job Title'),
        ),
    ]
