# Generated by Django 4.2.27 on 2025-12-26 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accidents', '0009_incident_affected_person_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_closed', to=settings.AUTH_USER_MODEL, verbose_name='Closed By'),
        ),
        migrations.AddField(
            model_name='incident',
            name='is_recurrence_possible',
            field=models.BooleanField(default=False, verbose_name='Is Recurrence Possible?'),
        ),
        migrations.AddField(
            model_name='incident',
            name='lessons_learned',
            field=models.TextField(blank=True, help_text='Key learnings from this incident', verbose_name='Lessons Learned'),
        ),
        migrations.AddField(
            model_name='incident',
            name='preventive_measures',
            field=models.TextField(blank=True, help_text='Measures implemented to prevent recurrence', verbose_name='Preventive Measures'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='closure_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Closure Date'),
        ),
    ]
