# Generated by Django 4.2.27 on 2025-12-30 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0005_alter_sublocation_code'),
        ('accidents', '0010_incident_closed_by_incident_is_recurrence_possible_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='behalf_reporter_department',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='behalf_reporter_name',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='incident_title',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='is_reported_on_behalf',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='severity_level',
        ),
        migrations.AddField(
            model_name='incident',
            name='affected_person',
            field=models.ForeignKey(blank=True, help_text='Employee who was affected by the incident', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_as_affected_person', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incident',
            name='sublocation',
            field=models.ForeignKey(blank=True, help_text='Optional: Specific sub-location where incident occurred', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='organizations.sublocation'),
        ),
        migrations.AddField(
            model_name='incident',
            name='unsafe_acts_other',
            field=models.TextField(blank=True, help_text="Explanation for 'Other' unsafe acts"),
        ),
        migrations.AddField(
            model_name='incident',
            name='unsafe_conditions_other',
            field=models.TextField(blank=True, help_text="Explanation for 'Other' unsafe conditions"),
        ),
        migrations.AlterField(
            model_name='incident',
            name='affected_person_age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='affected_person_dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_closed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incident',
            name='closure_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_type',
            field=models.CharField(choices=[('LTI', 'Lost Time Injury (LTI)'), ('MTC', 'Medical Treatment Case (MTC/RWC)'), ('FA', 'First Aid (FA)'), ('HLFI', 'High Lost Frequency Injury (HLFI)'), ('FATALITY', 'Fatality')], max_length=10),
        ),
        migrations.AlterField(
            model_name='incident',
            name='is_recurrence_possible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='incident',
            name='lessons_learned',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='nature_of_injury',
            field=models.TextField(help_text='Required: Describe the type and extent of injury'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='preventive_measures',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='incidentinvestigationreport',
            name='job_factors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='incidentinvestigationreport',
            name='personal_factors',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
