# Generated by Django 4.2.27 on 2025-12-31 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0011_remove_incident_behalf_reporter_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='affected_person_age',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='affected_person_dob',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='affected_person_employment_type',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='affected_person_gender',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='affected_person_job_title',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='first_aid_provided',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='hospital_name',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='hospitalization_required',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='immediate_actions_taken',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='witnesses',
        ),
    ]
