# Generated by Django 4.2.27 on 2026-01-02 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0012_remove_incident_affected_person_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentinvestigationreport',
            name='long_term_recommendations',
        ),
    ]
