# Generated by Django 4.2.27 on 2026-01-06 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0013_remove_incidentinvestigationreport_long_term_recommendations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentinvestigationreport',
            name='action_items',
        ),
        migrations.RemoveField(
            model_name='incidentinvestigationreport',
            name='target_completion_date',
        ),
    ]
