# Generated by Django 4.2.27 on 2026-01-06 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accidents', '0014_remove_incidentinvestigationreport_action_items_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('INCIDENT_REPORTED', 'Incident Reported'), ('INVESTIGATION_DUE', 'Investigation Due Soon'), ('INVESTIGATION_OVERDUE', 'Investigation Overdue'), ('ACTION_ASSIGNED', 'Action Item Assigned'), ('ACTION_DUE', 'Action Item Due Soon'), ('INCIDENT_CLOSED', 'Incident Closed'), ('INCIDENT_REOPENED', 'Incident Reopened')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accidents.incident')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='accidents_i_recipie_3b3279_idx'), models.Index(fields=['-created_at'], name='accidents_i_created_093683_idx')],
            },
        ),
    ]
