# Generated by Django 4.2.27 on 2025-12-16 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0003_alter_location_options_zone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hazard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_number', models.CharField(db_index=True, editable=False, max_length=50, unique=True)),
                ('reporter_name', models.CharField(max_length=200)),
                ('reporter_email', models.EmailField(max_length=254)),
                ('reporter_phone', models.CharField(blank=True, max_length=10)),
                ('hazard_title', models.CharField(max_length=255)),
                ('hazard_description', models.TextField(help_text='Detailed description of the hazard')),
                ('hazard_category', models.CharField(choices=[('slip_trip_fall', 'Slip/Trip/Fall'), ('chemical', 'Chemical'), ('electrical', 'Electrical'), ('fire', 'Fire'), ('equipment', 'Equipment/Machinery'), ('ergonomic', 'Ergonomic'), ('biological', 'Biological'), ('environmental', 'Environmental'), ('confined_space', 'Confined Space'), ('working_at_height', 'Working at Height'), ('manual_handling', 'Manual Handling'), ('noise', 'Noise/Vibration'), ('temperature', 'Temperature Extremes'), ('radiation', 'Radiation'), ('vehicular', 'Vehicular/Traffic'), ('other', 'Other')], max_length=30)),
                ('incident_datetime', models.DateTimeField(help_text='Date and time when hazard was identified')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], help_text='Severity level of the hazard', max_length=20)),
                ('location_details', models.TextField(blank=True, help_text='Additional location information')),
                ('gps_latitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS latitude coordinate', max_digits=10, null=True)),
                ('gps_longitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS longitude coordinate', max_digits=10, null=True)),
                ('injury_status', models.CharField(blank=True, help_text='Whether anyone was injured (yes/no)', max_length=10)),
                ('immediate_action', models.TextField(blank=True, help_text='Immediate actions taken to address the hazard')),
                ('witnesses', models.TextField(blank=True, help_text='Names and contact details of witnesses')),
                ('report_timestamp', models.DateTimeField(auto_now_add=True, help_text='Timestamp when report was submitted')),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent information')),
                ('report_source', models.CharField(default='web_portal', help_text='Source of the report (web_portal, mobile_app, etc.)', max_length=50)),
                ('reported_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('REPORTED', 'Reported'), ('UNDER_REVIEW', 'Under Review'), ('ACTION_ASSIGNED', 'Action Assigned'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], db_index=True, default='REPORTED', max_length=30)),
                ('corrective_action_plan', models.TextField(blank=True, help_text='Planned corrective actions to address the hazard')),
                ('action_deadline', models.DateField(blank=True, help_text='Deadline for completing corrective actions', null=True)),
                ('action_completed_date', models.DateField(blank=True, help_text='Date when corrective actions were completed', null=True)),
                ('closure_date', models.DateField(blank=True, help_text='Date when hazard was closed', null=True)),
                ('closure_remarks', models.TextField(blank=True, help_text='Remarks about hazard closure')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='User assigned to resolve the hazard', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hazards_assigned', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(help_text='Specific location where hazard exists', on_delete=django.db.models.deletion.CASCADE, related_name='hazards', to='organizations.location')),
                ('plant', models.ForeignKey(help_text='Plant where hazard was identified', on_delete=django.db.models.deletion.CASCADE, related_name='hazards', to='organizations.plant')),
                ('reported_by', models.ForeignKey(help_text='User who reported the hazard', on_delete=django.db.models.deletion.CASCADE, related_name='hazards_reported', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(blank=True, help_text='Zone within the plant', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hazards', to='organizations.zone')),
            ],
            options={
                'verbose_name': 'Hazard Report',
                'verbose_name_plural': 'Hazard Reports',
                'ordering': ['-incident_datetime', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HazardPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(help_text='Hazard photo (max 5MB)', upload_to='hazard_photos/%Y/%m/')),
                ('description', models.CharField(blank=True, help_text='Brief description of the photo', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('hazard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='hazards.hazard')),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded the photo', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hazard Photo',
                'verbose_name_plural': 'Hazard Photos',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='HazardActionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_description', models.TextField(help_text='Description of the action to be taken')),
                ('target_date', models.DateField(help_text='Target date for completing the action')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('OVERDUE', 'Overdue')], db_index=True, default='PENDING', max_length=20)),
                ('completion_date', models.DateField(blank=True, help_text='Date when action was completed', null=True)),
                ('completion_remarks', models.TextField(blank=True, help_text='Remarks about action completion')),
                ('verification_date', models.DateField(blank=True, help_text='Date when action was verified', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hazard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='hazards.hazard')),
                ('responsible_person', models.ForeignKey(help_text='Person responsible for completing the action', on_delete=django.db.models.deletion.CASCADE, related_name='hazard_actions_responsible', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, help_text='User who verified the action completion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hazard_actions_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hazard Action Item',
                'verbose_name_plural': 'Hazard Action Items',
                'ordering': ['target_date', '-created_at'],
                'indexes': [models.Index(fields=['status'], name='hazards_haz_status_82dfc0_idx'), models.Index(fields=['target_date'], name='hazards_haz_target__8991e3_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='hazard',
            index=models.Index(fields=['-incident_datetime'], name='hazards_haz_inciden_463b3e_idx'),
        ),
        migrations.AddIndex(
            model_name='hazard',
            index=models.Index(fields=['status'], name='hazards_haz_status_fd89dd_idx'),
        ),
        migrations.AddIndex(
            model_name='hazard',
            index=models.Index(fields=['severity'], name='hazards_haz_severit_7ff3c5_idx'),
        ),
        migrations.AddIndex(
            model_name='hazard',
            index=models.Index(fields=['hazard_category'], name='hazards_haz_hazard__efe515_idx'),
        ),
        migrations.AddIndex(
            model_name='hazard',
            index=models.Index(fields=['plant', 'location'], name='hazards_haz_plant_i_fafe72_idx'),
        ),
    ]
