# Generated by Django 4.2.27 on 2025-12-16 07:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hazards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hazard',
            name='incident_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when hazard was identified'),
        ),
    ]
