# Generated by Django 4.2.27 on 2025-12-16 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hazards', '0002_alter_hazard_incident_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='hazard',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='hazard',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hazards_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hazard',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hazard',
            name='approved_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='hazard',
            name='status',
            field=models.CharField(choices=[('REPORTED', 'Reported'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('UNDER_REVIEW', 'Under Review'), ('ACTION_ASSIGNED', 'Action Assigned'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], db_index=True, default='REPORTED', max_length=30),
        ),
    ]
