# Generated by Django 4.2.27 on 2025-12-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hazards', '0003_hazard_approval_status_hazard_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hazardactionitem',
            name='hazard_type',
            field=models.CharField(choices=[('UA', 'Unsafe Act'), ('UC', 'Unsafe Condition')], default=1, help_text='UA - Unsafe Act (behavior), UC - Unsafe Condition (environment)', max_length=2),
            preserve_default=False,
        ),
    ]
