# Generated by Django 4.2.27 on 2025-12-22 04:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hazards', '0005_remove_hazardactionitem_hazard_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hazard',
            name='forward_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hazard',
            name='forward_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hazard',
            name='forwarded_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwarding_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hazard',
            name='forwarded_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwarded_hazards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hazard',
            name='hazard_type',
            field=models.CharField(choices=[('UA', 'Unsafe Act'), ('UC', 'Unsafe Condition'), ('NM', 'Near Miss')], help_text='UA - Unsafe Act (behavior), UC - Unsafe Condition (environment)', max_length=2),
        ),
    ]
