# Generated by Django 4.2.27 on 2025-12-23 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_alter_sublocation_code'),
        ('hazards', '0006_hazard_forward_date_hazard_forward_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hazard',
            name='sublocation',
            field=models.ForeignKey(blank=True, help_text='Optional: Specific sub-location where hazard was observed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hazards', to='organizations.sublocation'),
        ),
        migrations.AddField(
            model_name='hazardphoto',
            name='photo_type',
            field=models.CharField(blank=True, choices=[('evidence', 'Evidence'), ('corrective_action', 'Corrective Action'), ('before', 'Before'), ('after', 'After')], default='evidence', max_length=20),
        ),
    ]
