# Generated by Django 4.2.27 on 2025-12-29 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_alter_sublocation_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hazards', '0007_hazard_sublocation_hazardphoto_photo_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='hazard',
            name='behalf_person',
            field=models.ForeignKey(blank=True, help_text='Employee on whose behalf report is being made', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hazards_reported_on_behalf', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hazard',
            name='behalf_person_dept',
            field=models.ForeignKey(blank=True, help_text='Department of person on whose behalf report is being made', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hazards_on_behalf', to='organizations.department'),
        ),
    ]
