# Generated by Django 4.2.27 on 2025-12-31 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hazards', '0008_hazard_behalf_person_hazard_behalf_person_dept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hazard',
            name='immediate_action',
        ),
    ]
