# Generated by Django 4.2.27 on 2025-12-24 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0005_alter_sublocation_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_number', models.CharField(max_length=100, unique=True, verbose_name='Inspection Number')),
                ('inspection_date', models.DateField(verbose_name='Inspection Date')),
                ('month', models.CharField(blank=True, max_length=20, verbose_name='Month')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Year')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('overall_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Compliance Score (%)')),
                ('total_findings', models.IntegerField(default=0, verbose_name='Total Findings')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comments', models.TextField(blank=True, verbose_name='Review Comments')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('pdf_report', models.FileField(blank=True, null=True, upload_to='inspections/reports/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_inspections', to=settings.AUTH_USER_MODEL)),
                ('conducted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conducted_inspections', to=settings.AUTH_USER_MODEL, verbose_name='Conducted By (HOD)')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='organizations.department')),
            ],
            options={
                'verbose_name': 'Inspection',
                'verbose_name_plural': 'Inspections',
                'ordering': ['-inspection_date'],
            },
        ),
        migrations.CreateModel(
            name='InspectionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200, verbose_name='Category Name')),
                ('sequence_order', models.IntegerField(default=0, verbose_name='Sequence Order')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Inspection Category',
                'verbose_name_plural': 'Inspection Categories',
                'ordering': ['template', 'sequence_order', 'category_name'],
            },
        ),
        migrations.CreateModel(
            name='InspectionPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_point_text', models.TextField(verbose_name='Inspection Point')),
                ('sequence_order', models.IntegerField(default=0, verbose_name='Sequence Order')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='Is Mandatory')),
                ('requires_photo', models.BooleanField(default=False, verbose_name='Requires Photo Evidence')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_points', to='inspections.inspectioncategory')),
            ],
            options={
                'verbose_name': 'Inspection Point',
                'verbose_name_plural': 'Inspection Points',
                'ordering': ['category', 'sequence_order'],
            },
        ),
        migrations.CreateModel(
            name='InspectionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=200, verbose_name='Template Name')),
                ('template_code', models.CharField(max_length=50, unique=True, verbose_name='Template Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('frequency', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('HALF_YEARLY', 'Half-Yearly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=20)),
                ('document_number', models.CharField(blank=True, max_length=100, verbose_name='Document Number')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inspection Template',
                'verbose_name_plural': 'Inspection Templates',
                'ordering': ['template_name'],
            },
        ),
        migrations.CreateModel(
            name='InspectionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField(verbose_name='Scheduled Date')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('notes', models.TextField(blank=True, verbose_name='Assignment Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_inspections', to=settings.AUTH_USER_MODEL, verbose_name='Assigned By (Safety Officer)')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_inspections', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To (HOD)')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_schedules', to='organizations.location')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_schedules', to='organizations.plant')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='inspections.inspectiontemplate')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_schedules', to='organizations.zone')),
            ],
            options={
                'verbose_name': 'Inspection Schedule',
                'verbose_name_plural': 'Inspection Schedules',
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='InspectionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('NA', 'N/A')], max_length=10, verbose_name='Response')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarks / Action Required')),
                ('photo_1', models.ImageField(blank=True, null=True, upload_to='inspections/photos/%Y/%m/')),
                ('photo_2', models.ImageField(blank=True, null=True, upload_to='inspections/photos/%Y/%m/')),
                ('photo_3', models.ImageField(blank=True, null=True, upload_to='inspections/photos/%Y/%m/')),
                ('sequence_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='inspections.inspectioncategory')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='inspections.inspection')),
                ('inspection_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='inspections.inspectionpoint')),
            ],
            options={
                'verbose_name': 'Inspection Response',
                'verbose_name_plural': 'Inspection Responses',
                'ordering': ['inspection', 'sequence_order'],
                'unique_together': {('inspection', 'inspection_point')},
            },
        ),
        migrations.CreateModel(
            name='InspectionFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finding_number', models.CharField(max_length=100, unique=True, verbose_name='Finding Number')),
                ('inspection_point_text', models.TextField(verbose_name='Inspection Point')),
                ('category_name', models.CharField(max_length=200, verbose_name='Category')),
                ('remarks', models.TextField(verbose_name='Finding Remarks')),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical (7 days)'), ('HIGH', 'High (15 days)'), ('MEDIUM', 'Medium (30 days)'), ('LOW', 'Low (45 days)')], default='MEDIUM', max_length=20)),
                ('target_date', models.DateField(verbose_name='Target Date')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('UNDER_REVIEW', 'Under Review'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected')], default='OPEN', max_length=20)),
                ('action_taken_description', models.TextField(blank=True, verbose_name='Action Taken Description')),
                ('action_taken_photo_1', models.ImageField(blank=True, null=True, upload_to='inspections/findings/%Y/%m/')),
                ('action_taken_photo_2', models.ImageField(blank=True, null=True, upload_to='inspections/findings/%Y/%m/')),
                ('action_taken_photo_3', models.ImageField(blank=True, null=True, upload_to='inspections/findings/%Y/%m/')),
                ('closure_date', models.DateField(blank=True, null=True, verbose_name='Closure Date')),
                ('closure_remarks', models.TextField(blank=True, verbose_name='Closure Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Assigned By (Safety Officer)')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_findings', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To (Responsible Person)')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_findings', to=settings.AUTH_USER_MODEL)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='inspections.inspection')),
                ('inspection_response', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finding', to='inspections.inspectionresponse')),
            ],
            options={
                'verbose_name': 'Inspection Finding',
                'verbose_name_plural': 'Inspection Findings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='inspectioncategory',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='inspections.inspectiontemplate'),
        ),
        migrations.CreateModel(
            name='InspectionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='inspections/attachments/%Y/%m/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(blank=True, max_length=50)),
                ('file_size', models.IntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('finding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='inspections.inspectionfinding')),
                ('inspection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='inspections.inspection')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inspection Attachment',
                'verbose_name_plural': 'Inspection Attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='inspection',
            name='inspection_schedule',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspection', to='inspections.inspectionschedule'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='organizations.location'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='organizations.plant'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_inspections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspection',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='inspections.inspectiontemplate'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='organizations.zone'),
        ),
        migrations.AlterUniqueTogether(
            name='inspectioncategory',
            unique_together={('template', 'category_name')},
        ),
    ]
