# Generated by Django 4.2.27 on 2025-12-12 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='email',
            new_name='contact_email',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='phone',
            new_name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='department',
            name='plant',
        ),
        migrations.AddField(
            model_name='department',
            name='head_email',
            field=models.EmailField(blank=True, help_text='Department Head Email', max_length=254),
        ),
        migrations.AddField(
            model_name='department',
            name='head_name',
            field=models.CharField(blank=True, help_text='Department Head Name', max_length=100),
        ),
        migrations.AddField(
            model_name='department',
            name='head_phone',
            field=models.CharField(blank=True, help_text='Department Head Phone', max_length=15),
        ),
        migrations.AddField(
            model_name='plant',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
