# Generated by Django 4.2.27 on 2025-12-22 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_location_options_zone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sublocations', to='organizations.location')),
            ],
            options={
                'verbose_name': 'Sub-Location',
                'verbose_name_plural': 'Sub-Locations',
                'ordering': ['location', 'name'],
                'unique_together': {('location', 'code')},
            },
        ),
    ]
