# Generated by Django 4.2.27 on 2025-12-22 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_sublocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sublocation',
            name='code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
