# Generated by Django 4.2.27 on 2025-12-31 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_alter_sublocation_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sublocation',
            unique_together=set(),
        ),
    ]
